[package]
name = "devefi-jes1-icpneuron"
version = "0.2.3"
description = "Stake ICP neurons and receive maturity directly to your destination"
repository = "https://github.com/jesssekeogh/devefi_jes1_icpneuron"
keywords = [ "devefi", "neuron", "stake", "icp" ]
license = ""

[dependencies]
base = "0.13.3"
neuro = "0.8.0"
map = "9.0.1"

[dev-dependencies]
devefi = "0.4.0"