[package]
name = "devefi-jes1-icpneuron"
version = "0.1.0"
description = "Stake ICP neurons and receive maturity directly to your destination."
repository = "https://github.com/jesssekeogh/devefi_jes1_icpneuron"
keywords = [ "devefi", "neuron", "stake", "icp" ]
license = ""

[dependencies]
base = "0.13.2"
devefi = "0.3.16"
neuro = "0.7.1"
map = "9.0.1"
vector = "0.4.1"

[dev-dependencies]
test = "2.0.0"